services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=product-ordering
    ports:
      - '27017:27017'
    restart: always
    networks:
      - orion

  redis:
    image: redis:6.2-alpine
    restart: always
    networks:
      - orion
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass denisOtami
    volumes:
      - redis:/data

  product-ordering-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongo:27017/product-ordering
      - ORIGIN=http://localhost:9001
      - REDIS_PORT=6379
      - REDIS_PASSWORD=denisOtami
      - REDIS_URL=redis://redis:6379

    volumes:
      - .:/usr/src/app
    restart: always
    env_file:
      - .env.development
    depends_on:
      - mongo
      - redis
    networks:
      - orion

networks:
  orion:
    driver: bridge

volumes:
  redis:
