version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    restart: always
