name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Login to Heroku Container Registry
      run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

    - name: Tag Docker image for Heroku
      run: docker tag my-image-name:$(date +%s) registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Push Docker image to Heroku
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

    - name: Release Docker image on Heroku
      run: |
        curl -n -X PATCH https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/formation \
        -d '{
          "updates": [
            {
              "type": "web",
              "docker_image": "registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web"
            }
          ]
        }' \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}"
